### ISSUE TITLE
křivé odrazy od desky

### ISSUE THREAD

**Issue by mjirik** [mjirik/pycanoid#1]

**Comment by somapatrik** [comment]
Funguje, občas se odrazí zvláštně. Nepochopil jsem nový výpočet úhlu

**Comment by mjirik** [comment]
jde o to, aby se kulička od desky odrážela v závislosti na tom, kde ji zasáhne. Pravidlo "úhel dopadu = úhel odrazu" platí jen při zásahu do středu desky. Směrem k okrajům se deska tváří, jako by měla trochu oblé tvary. Viz video

http://www.youtube.com/watch?v=kbvN_PupAiY

**Comment by somapatrik** [comment]
To jsem pochopil a taky jsem to tak udělal. Rozdělil jsem desky na tři části, jde mi jenom o to, že odraz není tak "čistý" jako předtím. Prodiskutoval bych to osobně, jde jenom o to, jestli jsem správně pozměnil úhel při odrazu na stranách.

**Comment by mjirik** [comment]
zkusil jsem to, myslím, že jako první nástřel je to dobré. Trochu se to trhá, no. Do budoucna bych tam ještě přidal nějaký podfuk, aby se to nedalo odrazit příliš vodorovně. Pak to trvá dlouho, než kulička přejede obrazovku. Zatím dobré.
