### ISSUE TITLE
překážky

### ISSUE THREAD

**Issue by mjirik** [mjirik/pycanoid#2]

**Comment by somapatrik** [comment]
Vytvořil jsem třídu Blocks, která vypočítá oblast, kde budou překážky a jejich velikost. Nastaví se tam kolik procent z herní oblasti to má zabírat a všechno se přepočítá. Podle toho všeho se vygeneruje numpy array s binárními daty, kde 0 reprezentuje prázdné místo a 1 překážku. Ještě mi nejde bloky vykreslit do hry, ale to se mi snad podaří ještě dneska.

 Zatím, ale netuším jak budu detekovat dopad kuličky na desku. Jenom dávám update

**Comment by mjirik** [comment]
bezva práce, díky za info

**Comment by somapatrik** [comment]
Beru zpět, vykreslení bloků není tak jednoduché jak jsem si myslel....

**Comment by mjirik** [comment]
:-D

**Comment by somapatrik** [comment]
Překážky se vykreslují, stačí zadat počet a rozměry se nastaví automaticky. Odraz kuličky funguje, ale  poněkud "hrubě". Na mizení překážky při dopadu ještě pracuji. Hra běží trochu pomaleji, protože se neustále kontrolují pozice překážek. Není to ještě 100%, ale jestli už funguje kinect tak se to může vyzkoušet propojit.

**Comment by somapatrik** [comment]
Zkusíme to?

**Comment by somapatrik** [comment]
Fungovalo to
